### PR TITLE
v3 (Severe changes)

### PR DESCRIPTION
**Pull request by USERSATOSHI**
this is a rewrite of dbdjsdb
with multiple db types

currently completed KeyValue Type

this rewrite contains:

1) rollback on unexpected process kill
2) read broken JSON 
3) fix them when using KeyValue#set / #delete
4) async queued system for faster read and write
5) encryption using crypto module 

## Issues Fixed
this rewrite also fix issues related to previous versions such as:
**data saved in same table** => if 2 or more tables were called at same time ,  instead of saving data separately , it saved all data in first one.

**database error when json is incomplete** => when an unexpected process kill happens, sometimes the db is not able to complete the write part and JSON becomes incomplete which later breaks the db when reading the file.

**Sync read and write** => previous versions uses Sync methods for read and write. we know that Sync are faster but it becomes an issue when reading and writing multiple files.a quick execution check for 100k data shows that even if console.timeEnd returns 200 to 400ms the actual saving of the data in disk(file) takes much longer (around +5 sec)
giving this enough time to get corrupt 

## Plans
add relational
subRelational
Graph
Column
and a ws type Transmitter Reciever

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
as KeyValue is almost done 
i am now shifting to Columnar and relational 
first Columnar then relational

**Comment by Leref** [comment]
Amazing work, though many of these commits are testing but overall nice.

**Comment by USERSATOSHI** [comment]
yeah i was messing up the tests cause  i forgot some files that tests were using were in gitignore :-)

**Comment by Leref** [comment]
Switching this repo to https://github.com/Leref/aoi.db
To differ the packages.

**Comment by USERSATOSHI** [comment]
merged in new

**Pull request closed without merging**
